version: '3.9'

networks:
  dev_network:

services:
  db:
    image: postgres:14.3-alpine3.15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: admin
      POSTGRES_DB: flask_test_use
    networks:
      - dev_network

  dbadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:5.7
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@mail.ru"
      PGADMIN_DEFAULT_PASSWORD: "adminpwd"
      PGADMIN_CONFIG_SERVER_MODE: "false"
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart:
      unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
    networks:
      - dev_network




